services:
  web:
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - media_data:/app/media
    env_file:
      - .env.docker
    command: python manage.py runserver 0.0.0.0:8000
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    env_file:
      - .env.docker
    environment:
      POSTGRES_DB: vk_dz_3
      POSTGRES_USER: vk_user
      POSTGRES_PASSWORD: vk_password
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  media_data:
  pg_data:
